image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install && npm run db:seed
    name: Init
  - openMode: split-right
    command: npm run dev:server
    name: Server
  - openIn: bottom
    command: npm run dev:client
    name: Client

# Ports to expose on workspace startup (optional)
ports:
  - port: 8080
  - port: 5432
    onOpen: open-preview

